Importing modules

```{r}
library("forecast")
library("graphics")
library("TTR")
library("TSA")
library("rio")
library("ggplot2")
```

getting dataframe

```{r}
#get data
df<-read.csv("https://raw.githubusercontent.com/Rheyhan/MPDW-Rhey/master/Tugas/Harga%20Saham%20Lockheed%20Martin%20-%20Sheet1.csv")
n<-length(df[,1])
n
```

```{r}
#encode date into a numerical arange 
colnames(df)<-c("Week", "price")
df[,1]<-seq(1,n)
tail(df)
```

Data Exploration and Train-Test Split

```{r}
#Exploration of the dataframe
View(df)
str(df)
dim(df)
```

```{r}
df_ts=ts(df[,2])
#train test split (80 | 20)
train_data <- (df[1:(n*0.8),])
train_data
test_data <- df[(n*0.8+1):length(df[,1]),]
test_data
train_ts <- ts(train_data[,2])
test_ts <- ts(test_data[,2])
size<-cbind(length(train_ts),length(test_ts))
colnames(size)<-c("train", "test")
size
```

```{r}
ggplot() + 
  geom_line(data = train_data, aes(x = Week, y = price, col = "Train data")) +
  geom_line(data = test_data, aes(x = Week, y = price, col = "Test Data")) +
  labs(x = "Week", y = "Price (USD)", color = "Legend") +
  scale_colour_manual(name="Legend:", breaks = c("Train data", "Test Data"),
                      values = c("blue", "red")) + 
  theme_bw() + theme(legend.position = "bottom",
                     plot.caption = element_text(hjust=0.5, size=12))
#Data bukan tipe seasonly
```

Finding the best model dependent on its accuracy

```{r}
# SES
    #SES alpha 0.2
ses.1 <- ses(train_ts, h = 240, alpha = 0.2)
plot(ses.1)
ses.1

    #SES alpha 0.7
ses.2<- ses(train_ts, h = 240, alpha = 0.7)
plot(ses.2)
ses.2

    #(Holtwinter Function, alpha=0.2)
ses1<- HoltWinters(train_ts, gamma = FALSE, beta = FALSE, alpha = 0.2)
plot(ses1)

        #forecast
ramalan1<- forecast(ses1, h=240)
ramalan1

    #(Holtwinter Function, alpha=0.7)
ses2<- HoltWinters(train_ts, gamma = FALSE, beta = FALSE, alpha = 0.7)
plot(ses2)

        #forecast
ramalan2<- forecast(ses2, h=240)
ramalan2


    #SES Optimum Alpha
ses.opt <- ses(train_ts, h = 240, alpha = NULL)
plot(ses.opt)
ses.opt

    #Holtwinter optimum alpha
sesopt<- HoltWinters(train_ts, gamma = FALSE, beta = FALSE,alpha = NULL)
sesopt
plot(sesopt)

      #forecast
ramalanopt<- forecast(sesopt, h=240)
```

```{r}
#Get accuracy ses
selisih1<-ramalan1$mean-test_data$price
SSEtesting1<-sum(selisih1^2)
MSEtesting1<-SSEtesting1/length(test_data)

selisih2<-ramalan2$mean-test_data$price
SSEtesting2<-sum(selisih2^2)
MSEtesting2<-SSEtesting2/length(test_data)

selisihopt<-ramalanopt$mean-test_data$price
SSEtestingopt<-sum(selisihopt^2)
MSEtestingopt<-SSEtestingopt/length(test_data)

akurasitesting1 <- matrix(c(SSEtesting1,SSEtesting2,SSEtestingopt))
row.names(akurasitesting1)<- c("SSE1", "SSE2", "SSEopt")
akurasitesting1

akurasitesting2 <- matrix(c(MSEtesting1,MSEtesting2,MSEtestingopt))
row.names(akurasitesting2)<- c("MSE1", "MSE2", "MSEopt")
akurasitesting2

mergedtemp<-cbind(akurasitesting1, akurasitesting2)
row.names(mergedtemp)<-c("SES1", "SES2", "SSEopt")
colnames(mergedtemp)<-c("SSE", "MSE")
mergedtemp
```

```{r}
  #DES #Lamda=0.2 dan gamma=0.2
des.1<- HoltWinters(train_ts, gamma = FALSE, beta = 0.2, alpha = 0.2)
plot(des.1)

    #ramalan
ramalandes1<- forecast(des.1, h=240)
ramalandes1

  #DES Lamda=0.6 dan gamma=0.3
des.2<- HoltWinters(train_ts, gamma = FALSE, beta = 0.3, alpha = 0.6)
plot(des.2)

    #ramalan
ramalandes2<- forecast(des.2, h=240)
ramalandes2


  #Holwinter optimum Lamda gamma (Best model)
des.opt<- HoltWinters(train_ts, gamma = FALSE)
des.opt
plot(des.opt)

ramalandesopt<- forecast(des.opt, h=240)
ramalandesopt
```

```{r}
#get accuracy of DES
selisihdes1<-ramalandesopt$mean-test_data$price
selisihdes1

SSEtestingdes1<-sum(selisihdes1^2)
MSEtestingdes1<-SSEtestingdes1/length(test_data$price)
MAPEtestingdes1<-sum(abs(selisihdes1/test_data$price)*100)/length(test_data$price)

selisihdes2<-ramalandes2$mean-test_data$price
selisihdes2

SSEtestingdes2<-sum(selisihdes2^2)
MSEtestingdes2<-SSEtestingdes2/length(test_data$price)
MAPEtestingdes2<-sum(abs(selisihdes2/test_data$price)*100)/length(test_data$price)

selisihdesopt<-ramalandesopt$mean-test_data$price
selisihdesopt

SSEtestingdesopt<-sum(selisihdesopt^2)
MSEtestingdesopt<-SSEtestingdesopt/length(test_data$price)
MAPEtestingdesopt<-sum(abs(selisihdesopt/test_data$price)*100)/length(test_data$price)

akurasitestingdes <-
  matrix(c(SSEtestingdes1,MSEtestingdes1,MAPEtestingdes1,SSEtestingdes2,MSEtestingdes2,
           MAPEtestingdes2,SSEtestingdesopt,MSEtestingdesopt,MAPEtestingdesopt),
         nrow=3,ncol=3)
row.names(akurasitestingdes)<- c("SSE", "MSE", "MAPE")
colnames(akurasitestingdes) <- c("des ske1","des ske2","des opt")
akurasitestingdes
```

```{r}
#Comparing SES MSE and DES MSE. 
MSEfull <-
  matrix(c(MSEtesting1,MSEtesting2,MSEtestingopt,MSEtestingdes1,MSEtestingdes2,
           MSEtestingdesopt),nrow=3,ncol=2)
row.names(MSEfull)<- c("ske 1", "ske 2", "ske opt")
colnames(MSEfull) <- c("ses","des")
MSEfull
```

```{r}
#Comparing DES SKE OPT VS DES SKE1
Actual=c(rep(NA, 960), test_ts)
autoplot(ramalandesopt) +
  autolayer(fitted(ramalandesopt), series="Fitted") +
  ylab("Price (USD)") + xlab("week")
autoplot(ramalandes1) +
  autolayer(fitted(ramalandes1), series="Fitted") +
  ylab("Price (USD)") + xlab("week")      #incorrect
```

```{r}
#Using DES SKE OPT, it's preferably more accurate judging based on the visualization of actual test_data 
autoplot(ramalandesopt) +
  autolayer(fitted(ramalandesopt), series="Fitted") +
  ylab("Price (USD)") + xlab("week") + geom_line(data = test_data, aes(x = Week, y = price, col = "Actual data"))
```
