#Note 
Been changing dataset for like 4 times now bruh.💀

#import Modules

```{r}
library(metan)
library(car)
library(lmtest)
library(car)
library(randtests)
library(orcutt)
```

#get data Using <https://www.kaggle.com/datasets/yogesh94/m4-forecasting-competition-dataset?select=Monthly-train.csv>

```{r}
setwd("D:/Kuliah/!yes/R/Semester5/MPDW/Tugas/2")

rawdata=read.csv("Datasets/Monthly-train.csv")
head(rawdata)

#we'll just use n=2000 with v1-v3
n=2000
data=rawdata[1:n,1:5]

sum(is.na(data))           #No missing value

#changing categorical ordinal categorical into numerical ordinal
data["V1"]=seq(1, n)
colnames(data)[1]="Month"
```

#Get model

```{r}
summary(data)

plot(corr_coef(data))

#Regression Model (We'll use v2 as the predictor)
themodel<- lm(V2~V3+V4+V5, data)
themodel                     #Coef
summary(themodel)            #Get R, and both f and t test
anova(themodel)             #F test of each variable
```

###gauss markov assumptions

```{r}
#1. Nilai harapan themodel$residuals sama dengan nol
t.test(themodel$residuals,
       mu = 0,
       conf.level = 0.95)            #Passed pval==1

#2. Ragam themodel$residuals homogen
bptest(themodel)                     #Failed Pval<0.05

#3. themodel$residuals saling bebas
dwtest(themodel)                     #Failed Pval<0.05

#4. ASUMSI NORMALITAS themodel$residuals
shapiro.test(themodel$residuals)     #Failed Pval<0.05

#5.Tidak ada MULTIKOLINEARITAS 
vif(themodel)                        #Faj,ed |VIF|>10
```
###Visualization for those asumptions
```{r}
predicted<- predict(themodel)

par(mfrow = c(2,2))
qqnorm(themodel$residuals)
qqline(themodel$residuals, col = "steelblue", lwd = 2)

plot(predicted, themodel$residuals)
abline(a = 0, b = 0, lwd = 2)

hist(themodel$residuals, col = "steelblue")
plot(seq(1,n,1), themodel$residuals, col = "steelblue", pch = 20, xlab = "themodel$residuals", ylab = "Order", main = "themodel$residuals vs Order")

lines(seq(1,n,1), themodel$residuals, col = "red")
abline(a = 0, b = 0, lwd = 2)
```

#Handling Autocorellation
###Cochrane Orcutt method

```{r}
#using Cochrane Orcutt methoda
ThemodelCO <- cochrane.orcutt(themodel)
ThemodelCO

#Manual
optimumrho<- ThemodelCO$rho
optimumrho

#get transformed data
data.trans<-data.frame(V2 = (data$V2[-1]-data$V2[-n]*optimumrho),
                       V3 =(data$V3[-1]-data$V3[-n]*optimumrho),
                       V4 = (data$V4[-1]-data$V4[-n]*optimumrho),
                       V5 = (data$V5[-1]-data$V5[-n]*optimumrho))

#Testing gasus marcov asumptions on transformed data
model.trans <- lm(V2~V3+V4+V5, data.trans)

#Check for Autocorr
  #dw test
dwtest(model.trans)                                                   #passed
```

###Hildreth-Lu Method
```{r}
hildreth.lu.func<- function(r, model){
  x <- model.matrix(model)[,-1]
  y <- model.response(model.frame(model))
  n <- length(y)
  t <- 2:n
  y <- y[t]-r*y[t-1]
  x <- x[t]-r*x[t-1]
  
  return(lm(y~x))
}

#Pencariab rho yang meminimumkan SSE
r <- c(seq(0.1,0.9, by= 0.02))
tab <- data.frame("rho" = r, "SSE" = sapply(r, function(i){deviance(hildreth.lu.func(i, themodel))}))
round(tab, 4)

rOpt <- seq(0.1,0.9, by= 0.001)
tabOpt <- data.frame("rho" = rOpt, "SSE" = sapply(rOpt, function(i){deviance(hildreth.lu.func(i, themodel))}))
head(tabOpt[order(tabOpt$SSE),])
Optmimumrho=tabOpt[tabOpt$SSE==min(tabOpt$SSE),"rho"]
#visualization
par(mfrow = c(1,1))
plot(tab$SSE ~ tab$rho , type = "l", xlab = "Rho", ylab = "SSE")
abline(v = Optmimumrho, lty = 2, col="red",lwd=2)
```
```{r}
modelHL <- hildreth.lu.func(optimumrho, themodel)


#auto corellate test
  #dw test
dwtest(modelHL)                   #Failed pval<0.5
```
###Comparison
```{r}

#MSE comparison
#Get Sum sq of residual
sse.Normal <- anova(themodel)$`Sum Sq`[3]
sse.CO <- anova(model.trans)$`Sum Sq`[3]
sse.HL <- anova(modelHL)$`Sum Sq`[-1]

mse.Normal <- sse.Normal/n
mse.CO <- sse.CO/n
mse.HL <- sse.HL/n

akurasi <- matrix(c(sse.Normal,sse.CO,sse.HL,
                    mse.Normal,mse.CO,mse.HL),nrow=2,ncol=3,byrow = T)
mse.HL
colnames(akurasi) <- c("Model Awal", "Model Cochrane-Orcutt", "Model Hildreth-Lu")
row.names(akurasi) <- c("SSE","MSE")
akurasi

#dw test comparison
listdwtest<- matrix(c(as.numeric(dwtest(themodel)[4]), as.numeric(dwtest(model.trans)[4]), as.numeric(dwtest(modelHL)[4])),1, 3, T)

colnames(listdwtest) <- c("Model Awal", "Model Cochrane-Orcutt", "Model Hildreth-Lu")
listdwtest
```

